# Generated by Django 4.1.7 on 2023-06-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetcareapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=250)),
                ('message', models.TextField()),
                ('doctor', models.CharField(max_length=250)),
            ],
        ),
    ]
