# Generated by Django 4.1.7 on 2023-06-22 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vetcareapp', '0002_chatform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatform',
            old_name='owner',
            new_name='sender',
        ),
    ]
