# Generated by Django 4.1.7 on 2023-06-22 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vetcareapp', '0003_rename_owner_chatform_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatform',
            old_name='doctor',
            new_name='receiver',
        ),
    ]
