# Generated by Django 4.1.7 on 2023-05-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('phonenumber', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
            ],
        ),
    ]
