# Generated by Django 4.1.7 on 2023-05-25 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_consult_doctor_rename_registration_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='filename',
        ),
    ]
