# Generated by Django 4.1.7 on 2023-05-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_remove_doctor_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consult',
            name='address',
        ),
        migrations.AddField(
            model_name='consult',
            name='lat',
            field=models.IntegerField(default=10.5276),
            preserve_default=False,
        ),
    ]
