# Generated by Django 4.1.7 on 2023-05-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_remove_consult_address_consult_lat'),
    ]

    operations = [
        migrations.AddField(
            model_name='consult',
            name='lng',
            field=models.IntegerField(default=76.2144),
            preserve_default=False,
        ),
    ]
