# Generated by Django 4.1.7 on 2023-05-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_doctor_lat'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='lng',
            field=models.FloatField(default=76.275244),
            preserve_default=False,
        ),
    ]
